/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Persons.java
 *
 * Created on 04.12.2011, 20:32:47
 */
package com.offensand.movie.ui;

/**
 *
 * @author tvn
 */
public class PersonsUI extends javax.swing.JPanel {

  /** Creates new form Persons */
  public PersonsUI() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    personsName = new javax.swing.JTextField();
    jScrollDescr = new javax.swing.JScrollPane();
    jTextPaneDesc = new javax.swing.JTextPane();
    jPanelScenes = new javax.swing.JPanel();
    jTextSearch = new javax.swing.JTextField();
    jCheckShowScenes = new javax.swing.JCheckBox();
    jScrollScenes = new javax.swing.JScrollPane();
    jListScenes = new javax.swing.JList();
    jPanelActors = new javax.swing.JPanel();
    jPanelItems = new javax.swing.JPanel();
    jTextSearch1 = new javax.swing.JTextField();
    jCheckShowItems = new javax.swing.JCheckBox();
    jScrollItems = new javax.swing.JScrollPane();
    jListItems = new javax.swing.JList();

    personsName.setText("Persons name");

    jScrollDescr.setBorder(javax.swing.BorderFactory.createTitledBorder("Beschreibung"));
    jScrollDescr.setViewportView(jTextPaneDesc);

    jPanelScenes.setBorder(javax.swing.BorderFactory.createTitledBorder("Szenen"));

    jTextSearch.setText("Search Ex");

    jCheckShowScenes.setText("Zeige alle Scenen");

    jListScenes.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Scene 1", "Scene 2", "Scene 5", "Scene 6", "Scene 14" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jListScenes.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
    jListScenes.setVisibleRowCount(-1);
    jScrollScenes.setViewportView(jListScenes);

    javax.swing.GroupLayout jPanelScenesLayout = new javax.swing.GroupLayout(jPanelScenes);
    jPanelScenes.setLayout(jPanelScenesLayout);
    jPanelScenesLayout.setHorizontalGroup(
      jPanelScenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTextSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
      .addGroup(jPanelScenesLayout.createSequentialGroup()
        .addComponent(jCheckShowScenes)
        .addContainerGap(124, Short.MAX_VALUE))
      .addComponent(jScrollScenes, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
    );
    jPanelScenesLayout.setVerticalGroup(
      jPanelScenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelScenesLayout.createSequentialGroup()
        .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollScenes, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckShowScenes))
    );

    jPanelActors.setBorder(javax.swing.BorderFactory.createTitledBorder("Schauspieler"));

    javax.swing.GroupLayout jPanelActorsLayout = new javax.swing.GroupLayout(jPanelActors);
    jPanelActors.setLayout(jPanelActorsLayout);
    jPanelActorsLayout.setHorizontalGroup(
      jPanelActorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 274, Short.MAX_VALUE)
    );
    jPanelActorsLayout.setVerticalGroup(
      jPanelActorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 163, Short.MAX_VALUE)
    );

    jPanelItems.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items in Besitz"));

    jTextSearch1.setText("Search Ex");

    jCheckShowItems.setText("Zeige alle Items");

    jListItems.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 2", "Item 5", "Item 10", "Item 16" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jListItems.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
    jListItems.setVisibleRowCount(-1);
    jScrollItems.setViewportView(jListItems);

    javax.swing.GroupLayout jPanelItemsLayout = new javax.swing.GroupLayout(jPanelItems);
    jPanelItems.setLayout(jPanelItemsLayout);
    jPanelItemsLayout.setHorizontalGroup(
      jPanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTextSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
      .addGroup(jPanelItemsLayout.createSequentialGroup()
        .addComponent(jCheckShowItems)
        .addContainerGap(135, Short.MAX_VALUE))
      .addComponent(jScrollItems, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
    );
    jPanelItemsLayout.setVerticalGroup(
      jPanelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelItemsLayout.createSequentialGroup()
        .addComponent(jTextSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollItems, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckShowItems))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollDescr, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addGap(4, 4, 4))
          .addComponent(jPanelScenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(personsName, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanelActors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanelItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(personsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jPanelActors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanelScenes, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
          .addComponent(jPanelItems, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox jCheckShowItems;
  private javax.swing.JCheckBox jCheckShowScenes;
  private javax.swing.JList jListItems;
  private javax.swing.JList jListScenes;
  private javax.swing.JPanel jPanelActors;
  private javax.swing.JPanel jPanelItems;
  private javax.swing.JPanel jPanelScenes;
  private javax.swing.JScrollPane jScrollDescr;
  private javax.swing.JScrollPane jScrollItems;
  private javax.swing.JScrollPane jScrollScenes;
  private javax.swing.JTextPane jTextPaneDesc;
  private javax.swing.JTextField jTextSearch;
  private javax.swing.JTextField jTextSearch1;
  private javax.swing.JTextField personsName;
  // End of variables declaration//GEN-END:variables
}
